spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
  mvc:
    format:
      date: iso
      time: iso
      date-time: iso
  application:
    name: Currency Exchange
  jpa:
    show-sql: true
    database: h2
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./app # leaving this for creating H2 database samples, otherwise put some configuration following by README file
server:
  error:
    include-message: always
    include-binding-errors: always
