spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
  mvc:
    format:
      date: iso
      time: iso
      date-time: iso
  application:
    name: Currency Exchange
  data:
    rest:
      base-path: /api
      max-page-size: 100
      default-page-size: 20
      default-media-type: application/xml
      return-body-on-create: true
      return-body-on-update: true
  jpa:
    show-sql: true
    database: h2
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./app
    driver-class-name: org.h2.Driver
server:
  error:
    include-message: always
    include-binding-errors: always
