name: Test
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 21
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Test Gradle
        run: gradle test